import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const PlayerLeftPanel = ({ gameState, playerColor, playerName, isSpectator, }) => {
    if (!gameState) {
        return (_jsx("div", { className: "card-base", children: _jsx("div", { className: "text-dark-text-tertiary", children: "\u7B49\u5F85\u6E38\u620F\u5F00\u59CB..." }) }));
    }
    const isWaiting = gameState.status === 'waiting';
    const blackPlayer = gameState.players?.black;
    const isBlackTurn = gameState.currentPlayer === 1;
    return (_jsxs("div", { className: "card-base space-y-4", style: { backgroundColor: 'rgba(26, 31, 46, 0.5)' }, children: [isSpectator && (_jsx("div", { className: "p-3 rounded-lg bg-blue-500/20 border border-blue-500/50", children: _jsxs("div", { className: "text-sm text-blue-400", children: ["\uD83D\uDC41\uFE0F \u4F60\u6B63\u5728\u5B9E\u65F6\u89C2\u6218 - ", playerName] }) })), _jsxs("div", { className: `p-4 rounded-lg border-2 transition-colors ${isBlackTurn && !isWaiting
                    ? 'border-primary bg-primary/10'
                    : 'border-dark-text-tertiary/50 bg-dark-bg-tertiary'}`, children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx("div", { className: "w-4 h-4 rounded-full bg-black" }), _jsx("span", { className: "font-medium text-lg", children: "\u9ED1\u68CB" }), playerColor === 1 && _jsx("span", { className: "text-xs text-primary ml-auto", children: "(\u4F60)" })] }), _jsx("div", { className: "text-sm text-dark-text-secondary mt-2", children: blackPlayer?.name || playerName }), isBlackTurn && !isWaiting && (_jsx("div", { className: "mt-2 text-xs text-primary font-medium", children: "\u23F1\uFE0F \u6B63\u5728\u601D\u8003..." }))] }), _jsxs("div", { className: "pt-3 border-t border-dark-text-tertiary/20", children: [_jsx("div", { className: "text-base font-semibold text-dark-text-secondary mb-2", children: "\u6E38\u620F\u4FE1\u606F" }), _jsxs("div", { className: "space-y-1 text-sm", children: [_jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "\u6B65\u6570" }), _jsx("span", { className: "text-dark-text-secondary", children: gameState.moves?.length || 0 })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "\u5F53\u524D" }), _jsx("span", { className: "text-dark-text-secondary", children: isBlackTurn ? '黑棋' : '白棋' })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "\u72B6\u6001" }), _jsx("span", { className: "text-dark-text-secondary capitalize", children: isWaiting ? '等待中' : gameState.status })] })] })] })] }));
};
